// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Author.tsx";
import * as $$1 from "./islands/FAQ.tsx";
import * as $$2 from "./islands/Footer.tsx";
import * as $$3 from "./islands/Generator.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Author.tsx": $$0,
    "./islands/FAQ.tsx": $$1,
    "./islands/Footer.tsx": $$2,
    "./islands/Generator.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
